---
title: Room Squares
author: Matthew Henderson
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  bookdown::pdf_document2:
    fig_caption: yes
    toc: yes
    latex_engine: xelatex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
nocite: '@*'
bibliography: room-squares-bib/room-squares.bib
documentclass: book
classoption: a4paper
fontsize: 11pt
header-includes:
  - \usepackage[a4paper,margin=2.5cm]{geometry}
  - \usepackage[ruled,vlined]{algorithm2e}
  - \usepackage{amsmath}
  - \usepackage{amsthm}
  - \newtheorem{theorem}{Theorem}
  - \newtheorem{lemma}[theorem]{Lemma}
  - \newtheorem{corollary}{Corollary}[theorem]
  - \newcounter{examplecounter}
  - \newenvironment{example}{\begin{quote} \refstepcounter{examplecounter} \textbf{Example \arabic{examplecounter}} \quad }{ \end{quote} }
graphics: yes
---

```{r init, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(
  cache      = FALSE,
  cache.path = "cache/",
  echo       = FALSE,
  warning    = FALSE,
  message    = FALSE,
  fig.path   = "figure/",
  fig.width  = 6,
  fig.height = 4,
  comment    = "#>",
  collapse   = TRUE
)

ggplot2::theme_set(hrbrthemes::theme_ipsum_rc())
```
    
# Introduction

```{r introduction, child='chapters/01_introduction.Rmd'}
```

# A Graph-Theoretic Approach to Constructing Room Squares

```{r graph-theoretic, child='chapters/02_graph_theoretic.Rmd'}
```

# Proving the Existence of Room Squares

```{r existence-proof, child='chapters/03_existence_proof.Rmd'}
```

# An Existence Theorem for Room Squares

```{r existence-proof, child='chapters/04_existence_theorem.Rmd'}
```

# Balanced Room Squares

```{r balanced-room-squares, child='chapters/05_balanced_room_squares.Rmd'}
```

# Closing Remarks

```{r closing-remarks, child='chapters/06_closing_remarks.Rmd'}
```

# References
